### ISSUE TITLE
【Bug】语法高亮渲染不正确

### ISSUE THREAD

**Issue by TartaricAcid** [Snownee/language-mc-lang#3]
你永远不知道这些作者用了什么奇葩的`key`。    
只要`key`里面有空格或者`#`，渲染就彻底失效。

![Uploading 2018-01-18 10-51-32屏幕截图.png…](http://wx1.sinaimg.cn/large/cbd4d6d8ly1fnkkp8fc54j20nt099gn7.jpg)
![Uploading 2018-01-18 10-52-16屏幕截图.png…](http://wx3.sinaimg.cn/large/cbd4d6d8ly1fnkkp4ieguj20ff05uq3s.jpg)

**Comment by Snownee** [comment]
已在 0.4.2 中支持
