### ISSUE TITLE
[BUG]超过970个字符的条目不渲染

### ISSUE THREAD

**Issue by TartaricAcid** [Snownee/language-mc-lang#4]
如图所示：
![pic](http://wx4.sinaimg.cn/large/cbd4d6d8ly1fns177bq4kj21hc0u0kb6.jpg)

**Comment by Snownee** [comment]
这其实是个特性：

![image](https://user-images.githubusercontent.com/16059084/35335782-6f4d8c20-0151-11e8-9fc8-13c169a8f22f.png)

![image](https://user-images.githubusercontent.com/16059084/35335816-8962189c-0151-11e8-9bfe-28c9696fc6fc.png)

**Comment by Snownee** [comment]
atom/atom#1667 世界性的难题 😝

**Comment by Snownee** [comment]
似乎是目前可行的解决方案：
https://atom.io/packages/grammar-token-limit
